# 订阅配置
# subscribe-url:  # 当使用 MacOS 管理订阅时需填入订阅链接才会显示流量等信息 IOS 版可留空
proxy-providers:
  Conbine:
    type: http
    url: # 在此处填写你的订阅链接 作者使用的是 Sub Store 生成的链接
    interval: 600
    lazy: true
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 600

# 代理配置
port: 7890
socks-port: 7891
ipv6: false
mode: rule
tcp-concurrent: true
unified-delay: true
script:
  shortcuts:
    quic: network == 'udp' and dst_port == 443
hosts:
  time.facebook.com: 17.253.84.125
  time.android.com: 17.253.84.125
  mtalk.google.com: 108.177.125.188
  services.googleapis.cn: 74.125.203.94
dns:
  enable: true
  use-host: true
  default-nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 8.8.8.8
    - 1.1.1.1
    - 119.29.29.29
    - 122.112.208.1
    - system
  nameserver:
    - https://223.5.5.5/dns-query
    - https://1.12.12.12/dns-query
    - https://120.53.53.53/dns-query
    - https://doh.pub/dns-query
  fallback:
    - https://223.6.6.6/dns-query
    - https://dns.alidns.com/dns-query
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
  cache-algorithm: lru 
  cache-size: 1024 
  fallback-filter:
    geoip: true 
    geoip-code: CN 
    ipcidr:
      - 0.0.0.0/8 
      - 10.0.0.0/8
      - 127.0.0.0/8
      - 169.254.0.0/16 
      - 172.16.0.0/12 
      - 192.168.0.0/16
    domain:
      - "+.google.com"
      - "+.facebook.com"
      - "+.youtube.com"
      - "+.twitter.com"
      - "+.cloudflare.com"
      - "+.github.com"
log-level: warning
proxy-test-url:
  - https://www.gstatic.com/generate_204 # Google
  - https://www.baidu.com # 百度
  # - https://apple.com/library/test # 苹果
  # - https://cp.cloudflare.com/generate_204 # Cloudflare
http:
  url-rewrite:
    - ^https?://(www.)?g.cn($|/.*) https://www.google.com$2 302
    - ^https?://(www.)?google.cn($|/.*) https://www.google.com$2 302

# 策略组配置
proxy-groups:
  # 主策略组
  - name: 选择代理
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Proxy.png
    type: select
    interval: 120
    lazy: false
    proxies:
      - "美国 🇺🇲 US"
      - "香港 🇭🇰 HK"
      - "日本 🇯🇵 JP"
      - "欧洲 🇪🇺 EU"
      - "其它 🌏 OTHER"
      - "常用 ⭐ Common"
      - "自动 🔄 Auto"
      - "手动 🛠️ Manual"
      - DIRECT
  # 基于地区分组
  - name: "美国 🇺🇲 US"
    filter: "🇺🇲|US|美|美国|(?i)States|America"
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/United_States.png
    type: select
    interval: 120
    lazy: null
    include-all: true
  - name: "香港 🇭🇰 HK"
    filter: "🇭🇰|HK|港|香港|(?i)Hong"
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Hong_Kong.png
    type: select
    interval: 120
    lazy: true
    include-all: true
  - name: "日本 🇯🇵 JP"
    filter: "🇯🇵|JP|日|东京|(?i)Japan"
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Japan.png
    type: select
    interval: 120
    lazy: true
    include-all: true
  - name: "欧洲 🇪🇺 EU"
    filter: "🇪🇺|🇬🇧|🇫🇷|🇩🇪|🇺🇦|🇷🇺|EU|UK|欧盟|英|法|德|乌|俄"
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/European_Union.png
    type: select
    interval: 120
    lazy: true
    include-all: true
  - name: "其它 🌏 OTHER"
    filter: "^(?!.*(?i)(🇺🇲|🇭🇰|🇯🇵|🇪🇺|🇫🇷|🇩🇪|🇬🇧|🇷🇺|US|HK|JP|EU|France|Germany|UK|Russia|美国|香港|日本|法国|德国|英国|俄|流量|重置|剩余|套餐到期|套餐|flow)).*$"
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Area.png
    type: select
    interval: 120
    lazy: true
    include-all: true
  - name: "常用 ⭐ Common"
    filter: "^🇦🇺 澳大利亚Z01$|(?=.*美国)(?=.*05)|🇬🇧 英国"
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Static.png
    lazy: false
    type: select
    interval: 120
    include-all: true
  - name: "手动 🛠️ Manual"
    filter: "^(?!.*(?i)(免费|流量|重置|剩余|套餐到期|套餐)).*$"
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Available.png
    type: select
    interval: 120
    include-all: true
  - name: "自动 🔄 Auto"
    filter: "^(?!.*(?i)(免费|流量|重置|剩余|套餐到期|套餐)).*$"
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Auto.png
    url: https://www.gstatic.com/generate_204
    type: url-test
    interval: 120
    lazy: true
    tolerance: 30
    include-all: true
  - name: "测速 ⚡️ Speedtest"
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure/IconSet/Color/Speedtest.png
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 120
    tolerance: 30
    lazy: false
    proxies:
      - "常用 ⭐ Common"
      - "美国 🇺🇲 US"
      - "香港 🇭🇰 HK"
      - "日本 🇯🇵 JP"
      - "欧洲 🇪🇺 EU"
      - "其它 🌏 OTHER"
      - "手动 🛠️ Manual"
      - "自动 🔄 Auto"
  - name: "容错 🔧 Fail"
    type: fallback
    hidden: true
    url: https://www.gstatic.com/generate_204
    interval: 120
    timeout: 1500
    lazy: true
    proxies:
      - "常用 ⭐ Common"
      - "手动 🛠️ Manual"
      - "美国 🇺🇲 US"
      - "其它 🌏 OTHER"
      - "欧洲 🇪🇺 EU"
      - DIRECT
  - name: "订阅信息 🗂️"
    filter: "流量|(?i)flow|流量统计|流量监控|流量使用|流量使用情况|流量使用统计|流量使用监控|重置|到期|剩余|统计"
    icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Lab.png
    type: select
    interval: 120
    include-all: true
  - name: PROXY
    type: select
    hidden: true
    proxies:
      - 选择代理
    interval: 120
    lazy: true

# 远程规则集
rule-providers:
  cn-cidr:
    behavior: ipcidr
    format: text
    url: https://cdn.jsdelivr.net/gh/17mon/china_ip_list@master/china_ip_list.txt
    interval: 43200
  proxy-domain:
    behavior: domain
    format: yaml 
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt
    interval: 43200
  direct-domain:
    behavior: domain
    format: text
    url: https://cdn.jsdelivr.net/gh/Dhgaj/StashRules@main/domain-direct.txt
    interval: 43200
  adblock-domain:
    behavior: domain
    format: text 
    url: https://cdn.jsdelivr.net/gh/Dhgaj/StashRules@main/domain-adblock.txt
    interval: 43200

# 规则配置
rules:
  # == 以上为添加的规则 ==
  # == 特定服务分流 ==
  - DOMAIN-SUFFIX,spotify.com,美国 🇺🇲 US # Spotify 
  # == 远程规则集 ==
  - RULE-SET,cn-cidr,DIRECT,no-resolve # IP地址范围直连
  - RULE-SET,direct-domain,DIRECT # 直连规则
  - RULE-SET,adblock-domain,REJECT # 广告屏蔽
  - RULE-SET,proxy-domain,PROXY # 代理规则
  # == 默认规则 ==
  - GEOIP,LAN,DIRECT # 局域网 LAN 地址范围直连
  - GEOIP,CN,DIRECT # 中国大陆地址范围直连 可添加`no-resolve`以避免触发DNS解析
  - MATCH,PROXY # 默认规则，匹配所有流量